### ISSUE TITLE
FIX UR PORT

### ISSUE THREAD

**Issue by Randomxdp** [jigsaw-4277821/FNF-Psych-Engine-Android#1]
### Describe your bug here.

It has the same error i mentioned before : lua crashes after 3 secs and it crashes when it goes to main menu please fix your port 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by jigsaw-4277821** [comment]
You are eating shit

**Comment by Randomxdp** [comment]
Ok
