### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by arthurtse02** [jigsaw-4277821/FNF-Psych-Engine-Android#6]
### Describe your problem here.

I'm putting assets in com.shadowmario.psychengine and it's not working I've already tried to make a files folder and put assets in there but it still didn't work

I'm not using lua and I'm using android

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't program

**Comment by jigsaw-4277821** [comment]
Follow the instructions
